import type { AppShellNavItem } from '../../../types/ui';

export const integrationNavItems = [
  {
    id: 'overview',
    label: '总体概览',
    shortLabel: '总',
    group: 'overview',
    groupLabel: '总览',
    description: '平台状态、核心能力状态、待处理事项',
  },
  {
    id: 'business',
    label: '业务能力',
    shortLabel: '业',
    group: 'business',
    groupLabel: '业务能力',
    description: '业务版本、发布时间、默认入口',
  },
  {
    id: 'api-exposure',
    label: '接口调用',
    shortLabel: 'API',
    group: 'business',
    groupLabel: '业务能力',
    description: '业务 API 文档、Key、调用清单',
  },
  {
    id: 'ability-evals',
    label: '能力评测',
    shortLabel: '评',
    group: 'business',
    groupLabel: '业务能力',
    description: '工作流试运行、结果回填和评分',
  },
  {
    id: 'vendor-models',
    label: '模型弹药库',
    shortLabel: '模',
    group: 'arsenal',
    groupLabel: '能力弹药库',
    description: '第三方模型、密钥、出网与成本',
  },
  {
    id: 'apikeys',
    label: '历史密钥',
    shortLabel: '密',
    group: 'arsenal',
    groupLabel: '能力弹药库',
    description: '历史凭证配额管理',
  },
  {
    id: 'abilities',
    label: '能力目录',
    shortLabel: '能',
    group: 'arsenal',
    groupLabel: '能力弹药库',
    description: '原子能力列表、健康、测试与成本',
  },
  {
    id: 'executors',
    label: '运行线路',
    shortLabel: '线',
    group: 'execution',
    groupLabel: '运行保障',
    description: '能力运行线路、并发和健康',
  },
  {
    id: 'comfyui-management',
    label: 'ComfyUI 资源',
    shortLabel: '资',
    group: 'execution',
    groupLabel: '运行保障',
    description: 'LoRA/模型/模板',
  },
  {
    id: 'bindings',
    label: '路由策略',
    shortLabel: '路',
    group: 'execution',
    groupLabel: '运行保障',
    description: '能力入口到运行线路的分配规则',
    advanced: true,
  },
  {
    id: 'workflow-builder',
    label: '高级编排',
    shortLabel: '编',
    group: 'execution',
    groupLabel: '运行保障',
    description: 'Coze 编排画布与运行观察',
    advanced: true,
  },
  {
    id: 'ability-logs',
    label: '处理步骤',
    shortLabel: '调',
    group: 'usage',
    groupLabel: '调用与成本',
    description: '图片分析、生图、评分等后台步骤',
  },
  {
    id: 'billing',
    label: '账单框架',
    shortLabel: '账',
    group: 'usage',
    groupLabel: '调用与成本',
    description: '成本核对、流水、对账雏形',
    advanced: true,
  },
  {
    id: 'production-orders',
    label: '生产订单',
    shortLabel: '单',
    group: 'usage',
    groupLabel: '调用与成本',
    description: '核对生产文件、支付、蜂鸟订单和回传证据',
  },
  {
    id: 'monitor',
    label: '调度监控',
    shortLabel: '监',
    group: 'execution',
    groupLabel: '运行保障',
    description: '队列、任务和运行线路健康',
  },
  {
    id: 'logs',
    label: '调度事件',
    shortLabel: '事',
    group: 'usage',
    groupLabel: '调用与成本',
    description: '任务追踪',
    advanced: true,
  },
  {
    id: 'auth',
    label: '账号权限',
    shortLabel: '权',
    group: 'system',
    groupLabel: '系统与权限',
    description: '用户、会话、邀请码',
  },
  {
    id: 'system',
    label: '系统配置',
    shortLabel: '系',
    group: 'system',
    groupLabel: '系统与权限',
    description: '环境、OSS、待办',
  },
] as const satisfies readonly AppShellNavItem[];

export type IntegrationNavId = (typeof integrationNavItems)[number]['id'];

export const isIntegrationNavId = (value: string): value is IntegrationNavId =>
  integrationNavItems.some((item) => item.id === value);

export const isAdvancedIntegrationNav = (value: IntegrationNavId): boolean =>
  Boolean((integrationNavItems.find((item) => item.id === value) as AppShellNavItem | undefined)?.advanced);
