export type ToolField =
  | { key: string; label: string; type: 'textarea'; placeholder?: string; description?: string; advanced?: boolean }
  | { key: string; label: string; type: 'text'; placeholder?: string; description?: string; advanced?: boolean }
  | { key: string; label: string; type: 'number'; placeholder?: string; description?: string; advanced?: boolean }
  | { key: string; label: string; type: 'select'; options: Array<{ label: string; value: string }>; placeholder?: string; description?: string; advanced?: boolean };

export type RuntimeToolConfig = {
  abilityKey: string;
  abilityDisplayName: string;
  invokeMode: 'sync' | 'task';
  chainType?: 'core' | 'reuse';
  requiresImage?: boolean;
  imageSlots?: number;
  action: string;
  fields: ToolField[];
  defaults?: Record<string, string>;
  note?: string;
};

export const toolRuntimeConfig: Record<string, RuntimeToolConfig> = {
  'toolbox/upscale': {
    abilityKey: 'quality_upgrade',
    abilityDisplayName: 'AI超清',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-upscale',
    defaults: { resolution: '2k', type: 'auto' },
    fields: [
      { key: 'resolution', label: '输出分辨率', type: 'select', options: [{ label: '2K', value: '2k' }, { label: '4K', value: '4k' }] },
      { key: 'type', label: '增强模式', type: 'select', options: [{ label: '自动', value: 'auto' }, { label: '清晰度', value: 'clarity' }, { label: '细节', value: 'detail' }, { label: '纹理', value: 'texture' }] },
    ],
  },
  'toolbox/lossless-zoom': {
    abilityKey: 'upscale_resize',
    abilityDisplayName: '高质量缩放',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-lossless-zoom',
    defaults: { max_long_edge: '4096', output_format: 'png' },
    fields: [
      { key: 'max_long_edge', label: '长边像素', type: 'number', placeholder: '4096' },
      { key: 'output_format', label: '输出格式', type: 'select', options: [{ label: 'PNG', value: 'png' }, { label: 'JPG', value: 'jpg' }] },
    ],
  },
  'toolbox/outpaint': {
    abilityKey: 'huawen_kuotu',
    abilityDisplayName: 'AI扩图',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-outpaint',
    defaults: { expand_left: '160', expand_right: '160', expand_top: '0', expand_bottom: '0', size: '720' },
    fields: [
      { key: 'prompt', label: '扩图说明', type: 'textarea', placeholder: '描述扩图方向，例如保持原有面料风格并自然向左右延展。' },
      { key: 'expand_left', label: '左扩(px)', type: 'number' },
      { key: 'expand_right', label: '右扩(px)', type: 'number' },
      { key: 'expand_top', label: '上扩(px)', type: 'number' },
      { key: 'expand_bottom', label: '下扩(px)', type: 'number' },
      { key: 'size', label: '输出尺寸', type: 'number' },
    ],
  },
  'toolbox/resize': {
    abilityKey: 'upscale_resize',
    abilityDisplayName: '高质量缩放',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-resize',
    defaults: { max_long_edge: '2400', output_format: 'png' },
    fields: [
      { key: 'max_long_edge', label: '长边像素', type: 'number', placeholder: '2400' },
      { key: 'output_format', label: '输出格式', type: 'select', options: [{ label: 'PNG', value: 'png' }, { label: 'JPG', value: 'jpg' }] },
    ],
  },
  'toolbox/dpi': {
    abilityKey: 'set_dpi',
    abilityDisplayName: 'DPI处理',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-dpi',
    defaults: { dpi: '300' },
    fields: [{ key: 'dpi', label: '目标 DPI', type: 'number', placeholder: '300' }],
  },
  'design/text-to-style': {
    abilityKey: 'doubao_seedream_4_5',
    abilityDisplayName: '以文生款',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: false,
    action: 'client-text-to-style',
    defaults: { size: '2K' },
    fields: [
      { key: 'prompt', label: '设计提示词', type: 'textarea', placeholder: '例如：米白亚麻长裙，植物印花，轻复古，高级成衣质感。' },
      { key: 'size', label: '输出尺寸', type: 'select', options: [{ label: '2K', value: '2K' }, { label: '4K', value: '4K' }] },
    ],
  },
  'design/style-to-style': {
    abilityKey: 'nano_banana_pro_image_to_image',
    abilityDisplayName: '以款生款',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-style-to-style',
    defaults: { aspect_ratio: '1:1', resolution: '2K' },
    fields: [
      { key: 'prompt', label: '改款说明', type: 'textarea', placeholder: '描述要保留和变化的部分。' },
      { key: 'aspect_ratio', label: '输出比例', type: 'select', options: [{ label: '1:1', value: '1:1' }, { label: '3:4', value: '3:4' }, { label: '4:5', value: '4:5' }] },
      { key: 'resolution', label: '输出尺寸', type: 'select', options: [{ label: '1K', value: '1K' }, { label: '2K', value: '2K' }, { label: '4K', value: '4K' }] },
    ],
  },
  'design/sketch-to-style': {
    abilityKey: 'nano_banana_pro_image_to_image',
    abilityDisplayName: '线稿成款',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-sketch-to-style',
    note: '第一版先复用通用图生图链路，把线稿转成服装效果表达。',
    defaults: { aspect_ratio: '3:4', resolution: '2K' },
    fields: [
      { key: 'prompt', label: '成款说明', type: 'textarea', placeholder: '例如：保留线稿结构，生成高级成衣效果图，突出面料与层次。' },
      { key: 'aspect_ratio', label: '输出比例', type: 'select', options: [{ label: '3:4', value: '3:4' }, { label: '4:5', value: '4:5' }, { label: '1:1', value: '1:1' }] },
      { key: 'resolution', label: '输出尺寸', type: 'select', options: [{ label: '1K', value: '1K' }, { label: '2K', value: '2K' }] },
    ],
  },
  'design/style-to-sketch': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '款式线稿',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-style-to-sketch',
    note: '第一版先复用通用图像编辑链路，把成图转成线稿风格。',
    defaults: { aspect_ratio: '1:1', resolution: '1K' },
    fields: [
      { key: 'prompt', label: '线稿说明', type: 'textarea', placeholder: '例如：转为干净的服装设计线稿，保留轮廓和关键结构。' },
      { key: 'aspect_ratio', label: '输出比例', type: 'select', options: [{ label: '1:1', value: '1:1' }, { label: '3:4', value: '3:4' }] },
      { key: 'resolution', label: '输出尺寸', type: 'select', options: [{ label: '1K', value: '1K' }, { label: '2K', value: '2K' }] },
    ],
  },
  'design/fusion': {
    abilityKey: 'duotu_ronghe',
    abilityDisplayName: '融合创款',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 3,
    action: 'client-fusion',
    fields: [{ key: 'prompt', label: '融合说明', type: 'textarea', placeholder: '描述多张图要如何融合，例如保留图一轮廓、图二印花、图三配色。' }],
  },
  'design/pattern-extract': {
    abilityKey: 'yinhua_tiqu',
    abilityDisplayName: '图案提取',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-pattern-extract',
    defaults: { width: '1800', height: '1800' },
    fields: [
      { key: 'prompt', label: '提取说明', type: 'textarea', placeholder: '可补充图案提取要求，不填则走默认策略。' },
      { key: 'width', label: '输出宽度', type: 'number' },
      { key: 'height', label: '输出高度', type: 'number' },
    ],
  },
  'design/pattern-fusion': {
    abilityKey: 'duotu_ronghe',
    abilityDisplayName: '图案融合',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 3,
    action: 'client-pattern-fusion',
    fields: [{ key: 'prompt', label: '融合说明', type: 'textarea', placeholder: '描述图案融合方向，例如保留图一花型和图二主色。' }],
  },
  'design/local-redraw': {
    abilityKey: 'jisu_chuli',
    abilityDisplayName: '局部改款',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-local-redraw',
    note: '第一版先复用通用图像编辑链路，后续再补局部遮罩编辑器。',
    fields: [{ key: 'prompt', label: '改款说明', type: 'textarea', placeholder: '描述希望修改的局部，例如袖口、领型、花型位置。' }],
  },
  'design/garment-recolor': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '服装配色',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-garment-recolor',
    note: '第一版先复用图生图链路做服装换色。',
    fields: [{ key: 'prompt', label: '配色说明', type: 'textarea', placeholder: '例如：保留款式不变，将主色替换为米白和雾蓝。' }],
  },
  'design/ai-pattern': {
    abilityKey: 'doubao_seedream_4_5',
    abilityDisplayName: 'AI图案',
    invokeMode: 'sync',
    chainType: 'reuse',
    requiresImage: false,
    action: 'client-ai-pattern',
    defaults: { size: '2K' },
    fields: [
      { key: 'prompt', label: '图案提示词', type: 'textarea', placeholder: '例如：东方花卉，重复感强，适合女装印花，细节精致。' },
      { key: 'size', label: '输出尺寸', type: 'select', options: [{ label: '2K', value: '2K' }, { label: '4K', value: '4K' }] },
    ],
  },
  'design/pattern-recolor': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '图案配色',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-pattern-recolor',
    note: '第一版先复用图像编辑链路做图案配色尝试。',
    fields: [{ key: 'prompt', label: '配色说明', type: 'textarea', placeholder: '例如：保持花型不变，改成莫兰迪蓝绿系。' }],
  },
  'design/pattern-craft': {
    abilityKey: 'doubao_seedream_4_5',
    abilityDisplayName: '图案工艺',
    invokeMode: 'sync',
    chainType: 'reuse',
    requiresImage: false,
    action: 'client-pattern-craft',
    note: '第一版先复用文生图链路表达图案与工艺效果。',
    defaults: { size: '2K' },
    fields: [
      { key: 'prompt', label: '工艺说明', type: 'textarea', placeholder: '例如：刺绣+烫金+压纹感，突出图案工艺质感。' },
      { key: 'size', label: '输出尺寸', type: 'select', options: [{ label: '2K', value: '2K' }, { label: '4K', value: '4K' }] },
    ],
  },
  'design/seamless': {
    abilityKey: 'sifang_lianxu',
    abilityDisplayName: '四方连续',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-seamless',
    defaults: { patternType: 'seamless', width: '1024', height: '1024' },
    fields: [
      { key: 'prompt', label: '连续化说明', type: 'textarea', placeholder: '可补充连续化要求，例如边缘更自然、保留主花元素。' },
      { key: 'patternType', label: '连续类型', type: 'select', options: [{ label: '四方连续', value: 'seamless' }, { label: '两方连续', value: 'twoway' }] },
      { key: 'width', label: '输出宽度', type: 'number' },
      { key: 'height', label: '输出高度', type: 'number' },
    ],
  },
  'shoot/marketing-variants': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '裂变套图',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-marketing-variants',
    defaults: { resolution: '2K', aspect_ratio: '4:5' },
    fields: [
      { key: 'prompt', label: '套图说明', type: 'textarea', placeholder: '例如：保持服装主体一致，生成 3 张不同背景和构图的电商图。' },
      { key: 'resolution', label: '输出尺寸', type: 'select', options: [{ label: '1K', value: '1K' }, { label: '2K', value: '2K' }, { label: '4K', value: '4K' }] },
      { key: 'aspect_ratio', label: '输出比例', type: 'select', options: [{ label: '1:1', value: '1:1' }, { label: '4:5', value: '4:5' }, { label: '3:4', value: '3:4' }] },
    ],
  },
  'shoot/garment-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '服装上身',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-garment-tryon',
    note: '第一版先复用通用图生图能力，后续再补专用 try-on 链路。',
    fields: [{ key: 'prompt', label: '上身说明', type: 'textarea', placeholder: '例如：让服装自然挂到模特身上，保留版型与面料细节。' }],
  },
  'shoot/swap-background': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '换背景',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-swap-background',
    note: '第一版先复用通用图像编辑链路做背景替换。',
    fields: [{ key: 'prompt', label: '背景说明', type: 'textarea', placeholder: '例如：替换为干净棚拍背景或海边度假场景。' }],
  },
  'shoot/change-pose': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '换姿势',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-change-pose',
    note: '第一版先复用图像编辑链路尝试姿态变化。',
    fields: [{ key: 'prompt', label: '姿态说明', type: 'textarea', placeholder: '例如：改成轻微侧身、抬手展示细节。' }],
  },
  'shoot/garment-retouch': {
    abilityKey: 'zhongsu_tisheng',
    abilityDisplayName: '服装精修',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-garment-retouch',
    note: '第一版先复用中速提质链路做服装精修。',
    fields: [{ key: 'prompt', label: '精修说明', type: 'textarea', placeholder: '例如：增强面料纹理、轮廓清晰度和商业质感。' }],
  },
  'shoot/shoes-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '鞋类上脚',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-shoes-tryon',
    note: '第一版先复用通用图像编辑链路做鞋类上身效果。',
    fields: [{ key: 'prompt', label: '上脚说明', type: 'textarea', placeholder: '例如：生成鞋子穿着展示，突出鞋型和材质。' }],
  },
  'shoot/bag-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '包袋上身',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-bag-tryon',
    note: '第一版先复用通用图像编辑链路做包类上身效果。',
    fields: [{ key: 'prompt', label: '搭配说明', type: 'textarea', placeholder: '例如：生成包包自然背在模特身上的展示图。' }],
  },
  'shoot/hat-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '帽饰试戴',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-hat-tryon',
    note: '第一版先复用通用图像编辑链路做帽类上身效果。',
    fields: [{ key: 'prompt', label: '佩戴说明', type: 'textarea', placeholder: '例如：把帽子自然挂到模特头部，突出帽型。' }],
  },
  'shoot/image-to-video': {
    abilityKey: 'doubao_seedance_1_5_pro',
    abilityDisplayName: '图生视频',
    invokeMode: 'task',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-image-to-video',
    fields: [
      { key: 'prompt', label: '视频说明', type: 'textarea', placeholder: '例如：模特轻微转身，镜头平稳推进，保持服装纹理稳定。' },
      { key: 'duration', label: '时长(秒)', type: 'select', options: [{ label: '5 秒', value: '5' }, { label: '10 秒', value: '10' }] },
    ],
  },
  'shoot/garment-flatlay': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '服装平铺',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-garment-flatlay',
    note: '第一版先复用通用图像编辑链路做平铺表达。',
    fields: [{ key: 'prompt', label: '平铺说明', type: 'textarea', placeholder: '例如：转成规整平铺视角，背景简洁。' }],
  },
  'shoot/detail-shots': {
    abilityKey: 'quality_upgrade',
    abilityDisplayName: '细节图',
    invokeMode: 'sync',
    chainType: 'core',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-detail-shots',
    defaults: { resolution: '2k', type: 'detail' },
    fields: [
      { key: 'resolution', label: '输出分辨率', type: 'select', options: [{ label: '2K', value: '2k' }, { label: '4K', value: '4k' }] },
      { key: 'type', label: '增强重点', type: 'select', options: [{ label: '细节', value: 'detail' }, { label: '纹理', value: 'texture' }, { label: '自动', value: 'auto' }] },
    ],
  },
  'shoot/pattern-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '图案上身',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-pattern-tryon',
    note: '第一版先复用通用图生图链路做图案上身表达。',
    fields: [{ key: 'prompt', label: '上身说明', type: 'textarea', placeholder: '例如：让图案自然铺到服装主体上。' }],
  },
  'shoot/fabric-tryon': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '面料上身',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-fabric-tryon',
    note: '第一版先复用通用图生图链路做面料上身表达。',
    fields: [{ key: 'prompt', label: '面料说明', type: 'textarea', placeholder: '例如：把面料纹理自然挂到服装版型中。' }],
  },
  'shoot/curtain-preview': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '窗帘试挂',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-curtain-preview',
    note: '第一版先复用通用图像编辑链路做窗帘试挂效果。',
    fields: [{ key: 'prompt', label: '场景说明', type: 'textarea', placeholder: '例如：把窗帘自然挂到客厅落地窗场景。' }],
  },
  'toolbox/remove': {
    abilityKey: 'jisu_chuli',
    abilityDisplayName: 'AI消除',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-remove',
    note: '第一版先复用通用图像编辑链路做消除。',
    fields: [{ key: 'prompt', label: '消除说明', type: 'textarea', placeholder: '例如：去掉背景中的杂物和水印，保留主体。' }],
  },
  'toolbox/cutout': {
    abilityKey: 'jisu_chuli',
    abilityDisplayName: '智能抠图',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-cutout',
    note: '第一版先复用通用图像编辑链路做主体分离表达。',
    fields: [{ key: 'prompt', label: '抠图说明', type: 'textarea', placeholder: '例如：主体单独保留，背景尽量纯净。' }],
  },
  'toolbox/vectorize': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '转矢量风格',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-vectorize',
    note: '第一版先复用通用图像编辑链路尝试矢量化风格表达。',
    fields: [{ key: 'prompt', label: '矢量说明', type: 'textarea', placeholder: '例如：转成简洁清晰、适合继续描摹的矢量风格。' }],
  },
  'toolbox/recolor': {
    abilityKey: 'nano_banana_2_image_to_image',
    abilityDisplayName: '智能调色',
    invokeMode: 'task',
    chainType: 'reuse',
    requiresImage: true,
    imageSlots: 1,
    action: 'client-recolor',
    note: '第一版先复用通用图像编辑链路做调色。',
    fields: [{ key: 'prompt', label: '调色说明', type: 'textarea', placeholder: '例如：整体调整为暖灰米白商业风格。' }],
  },
};

const preferredAbilityPathMap: Record<string, string> = {
  quality_upgrade: '/toolbox/upscale',
  upscale_resize: '/toolbox/lossless-zoom',
  set_dpi: '/toolbox/dpi',
  huawen_kuotu: '/toolbox/outpaint',
  duotu_ronghe: '/design/fusion',
  yinhua_tiqu: '/design/pattern-extract',
  sifang_lianxu: '/design/seamless',
  jisu_chuli: '/design/local-redraw',
  zhongsu_tisheng: '/shoot/garment-retouch',
  nano_banana_pro_image_to_image: '/design/style-to-style',
  nano_banana_2_image_to_image: '/design/style-to-sketch',
  doubao_seedream_4_5: '/design/text-to-style',
  doubao_seedance_1_5_pro: '/shoot/image-to-video',
};

export function resolveWorkspacePathForTask(capabilityKey?: string | null, inputKeys: string[] = []) {
  const entries = Object.entries(toolRuntimeConfig).filter(([, config]) => config.abilityKey === capabilityKey);
  if (!entries.length) {
    return capabilityKey ? preferredAbilityPathMap[capabilityKey] || null : null;
  }
  if (entries.length === 1) {
    return `/${entries[0][0]}`;
  }
  let bestPath: string | null = null;
  let bestScore = Number.NEGATIVE_INFINITY;
  for (const [path, config] of entries) {
    const fieldKeys = new Set(config.fields.map((field) => field.key));
    let score = 0;
    for (const key of inputKeys) {
      score += fieldKeys.has(key) ? 3 : -1;
    }
    if (score > bestScore) {
      bestScore = score;
      bestPath = `/${path}`;
    }
  }
  return bestPath || (capabilityKey ? preferredAbilityPathMap[capabilityKey] || `/${entries[0][0]}` : `/${entries[0][0]}`);
}
